/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import javax.swing.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author EXPERTS
 */
public class AdminRole extends JFrame implements WindowNode  {
    AddLibrarian addLibrarian;
    ViewLibrarianWindow viewLibrarianWindow;
    RemoveLibrarian removeLibrarian;
    backend.AdminRole adminRoleB;
    WindowNode parentNode;
   
    /**
     * Creates new form AdminRole
     * @throws java.io.IOException
     */
    public AdminRole() throws IOException{
        parentNode = null;
        adminRoleB = new backend.AdminRole();
        viewLibrarianWindow = new ViewLibrarianWindow(new String[] {"Librarian Id","Name","Email","Address","Phone number"});
        removeLibrarian = new RemoveLibrarian(adminRoleB);
        addLibrarian = new AddLibrarian(adminRoleB);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewLibrarian = new javax.swing.JButton();
        remove_Librarian = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        addIibrarian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        viewLibrarian.setBackground(new java.awt.Color(0, 0, 0));
        viewLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        viewLibrarian.setText("View Librarians");
        viewLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLibrarianActionPerformed(evt);
            }
        });

        remove_Librarian.setBackground(new java.awt.Color(0, 0, 0));
        remove_Librarian.setForeground(new java.awt.Color(255, 255, 255));
        remove_Librarian.setText("Remove Librarian");
        remove_Librarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_LibrarianActionPerformed(evt);
            }
        });

        logOut.setBackground(new java.awt.Color(0, 0, 0));
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("Logout");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        addIibrarian.setBackground(new java.awt.Color(0, 0, 0));
        addIibrarian.setForeground(new java.awt.Color(255, 255, 255));
        addIibrarian.setText("Add Librarian");
        addIibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIibrarianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(remove_Librarian, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addIibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewLibrarian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(addIibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(viewLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(remove_Librarian, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addIibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIibrarianActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        addLibrarian.setParentNode(this);
        addLibrarian.setVisible(true);
        addLibrarian.setTitle("Add Librarian");
    }//GEN-LAST:event_addIibrarianActionPerformed

    private void viewLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLibrarianActionPerformed
        // TODO add your handling code here:
        backend.LibrarianData[] librarianDatas= adminRoleB.getListOfLibrarians();
        String[][] librarianDatases = new String[librarianDatas.length][5];
        for(int i = 0;i<librarianDatas.length;i++){
            librarianDatases[i]  = librarianDatas[i].lineRepresentation().split(",");
        }
        viewLibrarianWindow.setData(librarianDatases);
        viewLibrarianWindow.setTitle("View Librarian");
        this.setVisible(false);
        viewLibrarianWindow.setVisible(true);
        viewLibrarianWindow.setParentNode(this);
    }//GEN-LAST:event_viewLibrarianActionPerformed

    private void remove_LibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_LibrarianActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        removeLibrarian.setTitle("Remove Librarian");
        removeLibrarian.setVisible(true);
        removeLibrarian.setParentNode(this);
    }//GEN-LAST:event_remove_LibrarianActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
        try {
            adminRoleB.logout();
        } catch (IOException ex) {
            Logger.getLogger(AdminRole.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminRole().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AdminRole.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIibrarian;
    private javax.swing.JButton logOut;
    private javax.swing.JButton remove_Librarian;
    private javax.swing.JButton viewLibrarian;
    // End of variables declaration//GEN-END:variables

  @Override
    public void setParentNode(WindowNode parentNode) {
        this.parentNode = parentNode;
    }

    @Override
    public WindowNode getParentNode() {
        return this.parentNode;
    }

}
