/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author EXPERTS
 */
public class LibrarianRole extends JFrame implements WindowNode{
    AddBook addBook;
    ViewBooks viewBooks;
    BorrowBook borrowBook;
    ViewBorrowedBooks viewBorrowedBooks;
    ReturnBook returnBook;
    backend.LibrarianRole librarianRoleB;
    WindowNode parentNode;

    /**
     * Creates new form LibrarianRole
     * @throws java.io.IOException
     */
    public LibrarianRole() throws IOException {
        librarianRoleB = new backend.LibrarianRole();
        addBook = new AddBook(librarianRoleB);
        viewBooks = new ViewBooks(new String[]{"Book Id","Title","Auther Name","publisher","No of Copies"});
        borrowBook  = new BorrowBook();
        viewBorrowedBooks = new ViewBorrowedBooks(new String[] {"Student ID","Book ID", "Borrow Date"});
        returnBook = new ReturnBook();
        parentNode = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borrow_book_Button = new javax.swing.JButton();
        return_books_Button = new javax.swing.JButton();
        view_borrowed_books_Button = new javax.swing.JButton();
        logout_Button = new javax.swing.JButton();
        add_book_Button = new javax.swing.JButton();
        view_books_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        borrow_book_Button.setBackground(new java.awt.Color(0, 0, 0));
        borrow_book_Button.setForeground(new java.awt.Color(255, 255, 255));
        borrow_book_Button.setText("Borrow Book");
        borrow_book_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrow_book_ButtonActionPerformed(evt);
            }
        });

        return_books_Button.setBackground(new java.awt.Color(0, 0, 0));
        return_books_Button.setForeground(new java.awt.Color(255, 255, 255));
        return_books_Button.setText("Return Books");
        return_books_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_books_ButtonActionPerformed(evt);
            }
        });

        view_borrowed_books_Button.setBackground(new java.awt.Color(0, 0, 0));
        view_borrowed_books_Button.setForeground(new java.awt.Color(255, 255, 255));
        view_borrowed_books_Button.setText("View Borrow Book");
        view_borrowed_books_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_borrowed_books_ButtonActionPerformed(evt);
            }
        });

        logout_Button.setBackground(new java.awt.Color(0, 0, 0));
        logout_Button.setForeground(new java.awt.Color(255, 255, 255));
        logout_Button.setText("Logout");
        logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_ButtonActionPerformed(evt);
            }
        });

        add_book_Button.setBackground(new java.awt.Color(0, 0, 0));
        add_book_Button.setForeground(new java.awt.Color(255, 255, 255));
        add_book_Button.setText("Add Book");
        add_book_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_book_ButtonActionPerformed(evt);
            }
        });

        view_books_Button.setBackground(new java.awt.Color(0, 0, 0));
        view_books_Button.setForeground(new java.awt.Color(255, 255, 255));
        view_books_Button.setText("View Books");
        view_books_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_books_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(return_books_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(borrow_book_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_borrowed_books_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(logout_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(add_book_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(view_books_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(add_book_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_books_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(borrow_book_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_borrowed_books_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(return_books_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrow_book_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrow_book_ButtonActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
        borrowBook.setVisible(true);
    }//GEN-LAST:event_borrow_book_ButtonActionPerformed

    private void return_books_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_books_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        returnBook.setVisible(true);
    }//GEN-LAST:event_return_books_ButtonActionPerformed

    private void view_borrowed_books_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_borrowed_books_ButtonActionPerformed
        // TODO add your handling code here:
        backend.StudentBookData[] studentBookDatas = librarianRoleB.getListOfBorrowingOperations();
        String[][] studentBookDatases = new String[studentBookDatas.length][5];
        for (int i = 0 ;i<studentBookDatas.length;i++){
        studentBookDatases[i] = (studentBookDatas[i].lineRepresentation()).split(",");
        }
        viewBorrowedBooks.setData(studentBookDatases);
        viewBorrowedBooks.setParentNode(this);
        this.setVisible(false);
        viewBorrowedBooks.setVisible(true);
    }//GEN-LAST:event_view_borrowed_books_ButtonActionPerformed
    
    private void logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_logout_ButtonActionPerformed

    private void add_book_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_book_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        addBook.setVisible(true);
        addBook.setParentNode(this);
    }//GEN-LAST:event_add_book_ButtonActionPerformed

    private void view_books_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_books_ButtonActionPerformed
        // TODO add your handling code here:
        backend.BookData[] bookDatas = librarianRoleB.getListOfBooks();
        String[][] bookDatases = new String[bookDatas.length][5];
        for (int i = 0 ;i<bookDatas.length;i++){
        bookDatases[i] = (bookDatas[i].lineRepresentation()).split(",");
        }
        viewBooks.setData(bookDatases);
        this.setVisible(false);
        viewBooks.setVisible(true);
        viewBooks.setParentNode(this);
    }//GEN-LAST:event_view_books_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LibrarianRole().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(LibrarianRole.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_book_Button;
    private javax.swing.JButton borrow_book_Button;
    private javax.swing.JButton logout_Button;
    private javax.swing.JButton return_books_Button;
    private javax.swing.JButton view_books_Button;
    private javax.swing.JButton view_borrowed_books_Button;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(WindowNode parentNode) {
        this.parentNode = parentNode; 
    }

    @Override
    public WindowNode getParentNode() {
        return parentNode;
    }
}
